yatube/posts/urls.py
from posts import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('', views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
 ]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL, null=True,
        related_name='posts'
    )
    group = models.ForeignKey(
        "Group",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )

    class Meta:
        ordering = ("-pub_date",)


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=100)
    description = models.TextField(max_length=400)

    def __str__(self):
        return self.title

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from posts.models import Post, Group
from django.shortcuts import redirect


COUNT = 10


def index(request):
    posts = Post.objects.all()[:COUNT]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context=context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:COUNT]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context=context)


def only_user_view(request):
    if not request.user.is_authenticated:
        # Если пользователь не авторизован - отправляем его на страницу логина.
        return redirect('/auth/login/')
    # Если пользователь авторизован — здесь выполняется полезный код функции.

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="{% static 'img/fav/favicon.ico' %}" alt="">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}
       Последние изменения на сайте
    {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
          Контент не подвезли
        {% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
<!DOCTYPE html>
{% load static %}
    <header>
      {% load static %}
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="index.html">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>
        </div>
      </nav>
    </header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <h1>{{ group.title }}</h1>
    <p>{{ 'Лев Толстой – зеркало русской революции' }}</p>
    <article>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
        {{ post.text }}
      </p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
      </article>
    {% endfor %}
  <!-- под последним постом нет линии -->
{% endblock %}

yatube/templates/posts/index.html
<!-- templates/posts/index.html -->
{% extends 'base.html' %}
{% block title %}
  {{ title }}
{% endblock %}
{% block content %}
  <h1>{{ 'Последние обновления на сайте' }}</h1>
    {% for post in posts %}

      <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
       {{ post.text }}
      </p>
      <a href="group_list.html">все записи группы</a>
      </article>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
{% endblock %}